ogu/urls.py
from django.conf.urls import url, include
from django.views.generic.base import RedirectView
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(url='/pitaco/')),
    url(r'^fbmessenger/', include('juba.urls', namespace='juba')),
    url(r'^pitaco/', include('pitaco.urls', namespace='pitaco'))
]

pitaco/urls.py
from django.conf.urls import url, include
from .views import Pergunta, CSRFTemplateView

urlpatterns = [
    url(r'^$', CSRFTemplateView.as_view(template_name='inicio.html'), name='inicio', ),
    url(r'^pergunta$', Pergunta.as_view(), name='pergunta'),
]

pitaco/models.py
from django.db import models

# Create your models here.

pitaco/views.py
'''
Created on 25 de set de 2017

@author: Arndt
'''

from django.views.generic import View, TemplateView
from django.http import HttpResponseBadRequest, HttpResponseServerError, HttpResponse
# from django.template import RequestContext
from django.template.context_processors import csrf
from django.utils.cache import add_never_cache_headers
from django.conf import settings
from urllib.request import Request, urlopen
from urllib.parse import urlencode
from urllib.error import URLError
import logging

logger = logging.getLogger(__name__)

class Pergunta(View):
    http_method_names = ['post']

    def post(self, request, *args, **kwargs):
        if 'question' in request.POST:
            requisicao = Request(
                'https://westus.api.cognitive.microsoft.com/qnamaker/v1.0/knowledgebases/' \
                +settings.KBID+'/generateAnswer',
                data=bytes('{"question": "'+request.POST['question']+'"}', 'utf-8'),
                headers={'Ocp-Apim-Subscription-Key': settings.SUBSCRIPTION_KEY,
                        'Content-Type': 'application/json',
                        'Cache-Control': 'no-cache'},
                origin_req_host='https://westus.api.cognitive.microsoft.com/qnamaker/v1.0')
            #requisicao.add_header('Ocp-Apim-Subscription-Key', settings.SUBSCRIPTION_KEY)
            #requisicao.add_header('Content-Type', 'application/json')
            #requisicao.add_header('Cache-Control', 'no-cache')
            #requisicao.data = urlencode({"question": request.POST['question']}).encode('utf-8')
            try:
                resposta = urlopen(requisicao, timeout=30)
                resposta = resposta.read()
                resposta = HttpResponse(resposta, content_type='application/json')
                add_never_cache_headers(resposta)
                return resposta
            except URLError as e:
                logger.error(e.reason)
                logger.error(e.read())
                return HttpResponseServerError('Desculpe, minha mem&oacute;ria falhou. Que tal perguntar pelo [e-OUV](https://sistema.ouvidorias.gov.br/)?')
        else:
            return HttpResponseBadRequest()

class CSRFTemplateView(TemplateView):
    def get(self, request, *args, **kwargs):
        contexto = self.get_context_data(**kwargs)
        contexto['csrf_token']=  csrf(request)['csrf_token']
        return super(CSRFTemplateView, self).get(request, **contexto)

pitaco/templates/inicio.html
<!DOCTYPE html>
<html class="mdc-typography">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Pergunte-me! Ouvidorias.gov</title>
<link
      rel="stylesheet"
      href="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdn.rawgit.com/showdownjs/showdown/1.7.4/dist/showdown.min.js"></script>
<script type="text/javascript">
showdown.setOption('simplifiedAutoLink', true);
showdown.setOption('excludeTrailingPunctuationFromURLs', true);
showdown.setOption('openLinksInNewWindow', true);

inicio_resp = '<div class="mdc-card resposta"><section class="mdc-card__primary"><h1 class="mdc-card__title">'
inicio_perg = '<div class="mdc-card pergunta"><section class="mdc-card__primary"><h1 class="mdc-card__title">'
meio = '</section><section class="mdc-card__supporting-text">'
fim = '</section></div>'

$(document).ready(function() {
    $('#form_pergunta').on('submit', function(event) {
        $('#dialogo').append(inicio_perg + 'Você' + meio + $('#pergunta').val() +  fim);
        $("html, body").animate({ scrollTop: $(document).height() }, 1000);
        $.post(
               $('#form_pergunta').attr('action'),
               $('#form_pergunta').serialize(),
               function(data) {
                    if (data.score < 30 || data.answer == 'No good match found in the KB') {
                        data.answer = 'Desculpe-me, mas não sei responder. Que tal perguntar no [e-OUV](https://sistema.ouvidorias.gov.br/publico/Manifestacao/RegistrarManifestacao.aspx?tipo=5&orgaoDestinatario=52303&assunto=406)?'
                    }
                    converter     = new showdown.Converter(),
				    html          = converter.makeHtml(data.answer);
                    $('#dialogo').append(
                        /* '<div class="resposta"><div class="conteudo">' + */
                        inicio_resp + 'Ouvidorias.gov' + meio + html + fim);
                    $("html, body").animate({ scrollTop: $(document).height() }, 1000);
                    }
               );
        $('#pergunta').val('');
        return false;
    });
});
</script>
<style>
.container {
    max-width: 650px;
    margin: auto;
    }
.mdc-card {
    max-width: 550px;
    margin-bottom: 1rem;
    }
.resposta {
    margin-left: auto;
    background-color: lightblue;
    }
.resposta .mdc-card__title {
    text-align: right;
    }
.pergunta {
    background-color: lightgray;
    }
.mdc-card__title {
    font-weight: bold;
    }
</style>
</head>
<body>
<div class='container'>
<h1 class='mdc-typography--display1'>Pergunte-me!</h1>
<p>Tire suas dúvidas sobre as ouvidorias públicas! Faça uma pergunta abaixo,
e tentarei responder:</p>
    <div id='dialogo'>
	    <div class="mdc-card resposta">
          <section class="mdc-card__primary">
		    <h1 class="mdc-card__title">Ouvidorias.gov</h1>
		  </section>
	      <section class="mdc-card__supporting-text">
	         <p>Olá, em que posso ajudá-lo?</p>
          </section></div>
    </div>
	<form method='POST' action='{% url "pitaco:pergunta" %}' id='form_pergunta'>
	   {% csrf_token %}
		    <div class="mdc-textfield mdc-textfield--fullwidth mdc-card--theme-dark" data-mdc-auto-init="MDCTextfield">

				</section>
		        <input type='text' name='question' id='pergunta' autocomplete="off"
		        placeholder='Faça aqui sua pergunta!' class='mdc-textfield__input'
		        autofocus></input>
	        </div>
        <button type="submit"
	            class="mdc-button
	                   mdc-button--raised
	                   mdc-button--primary
	                   mdc-ripple-surface
	                   align-right"
	            data-mdc-auto-init="MDCRipple">
	        Enviar
	    </button>
    </form>
</div>

<!--  Material design -->
<script src="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.js"></script>
<script>window.mdc.autoInit();</script>
</body>
</html>